logging:
  level:
    com:
      ares:
        seckill:
          mapper: debug

spring:
  application:
    name: seckill-service
  redis:
    enable-multi: true
    multi:
      cn-redis:
          database: 1
          host: 127.0.0.1
          lettuce:
            pool:
              max-active: 1024
              max-idle: 200
              max-wait: 10000ms
              min-idle: 5
          password: ''
          port: 6379
          timeout: 100000ms
      hw-redis:
        database: 2
        host: 127.0.0.1
        lettuce:
          pool:
            max-active: 1024
            max-idle: 200
            max-wait: 10000ms
            min-idle: 5
        password: ''
        port: 6379
        timeout: 100000ms
  # thymeleaf 缓存配置
  thymeleaf:
    cache: false
server:
  port: 8090
